### PR TITLE
sg-22648-shotgrid replace shotgun instances

### PR DESCRIPTION
**Pull request by zamu5**

### CODE REVIEW

**Review by mathurf — COMMENTED** [review]
Need to replace `shotgun fields` by `ShotGrid fields` at line 121 in info.yml https://github.com/shotgunsoftware/tk-multi-workfiles2/blob/sg-22648-shotgrid/info.yml#L121

**Review by mathurf — APPROVED** [review]
Everything looks good on my side.

**Review by jfboismenu — APPROVED** [review]
I think you've likely broken automation. Could you revert some of those changes?

**Review by jfboismenu — APPROVED** [review]
Never mind my previous review. All good.

**Pull request merged**
